# Generated by Django 4.0.4 on 2022-06-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('ingredientes', models.CharField(max_length=40)),
                ('pasos', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='RecetasDulces',
        ),
    ]
